package com.mycompany.sistema_de_trafico.enums;

public enum TipoInterseccion {
    CRUCEMAS,
    CRUCET,
    CRUCETOPUESTA,
    CRUCETVOLTEADADERECHA,
    CRUCETVOLTEADAIZQUIERDA,
    CRUCEL,
    CRUCELOPUESTA,
    CRUCELVOLTEADADERECHA,
    CRUCELVOLTEADAIZQUIERDA
}